import { OverallListAction } from './getOverallList.action';
import { CountryListAction } from './getCountryList.action';

export enum CovidActionsTypes {
    GET_OVERALL_LIST = 'GET_OVERALL_LIST',
    GET_OVERALL_LIST_RESOLVING = 'GET_OVERALL_LIST_RESOLVING',
    GET_OVERALL_LIST_RESOLVED = 'GET_OVERALL_LIST_RESOLVED',
    GET_OVERALL_LIST_ERROR = 'GET_OVERALL_LIST_ERROR',
    RESET_GET_OVERALL_LIST = 'RESET_GET_OVERALL_LIST',
    GET_COUNTRY_LIST = 'GET_COUNTRY_LIST',
    GET_COUNTRY_LIST_RESOLVING = 'GET_COUNTRY_LIST_RESOLVING',
    GET_COUNTRY_LIST_RESOLVED = 'GET_COUNTRY_LIST_RESOLVED',
    GET_COUNTRY_LIST_ERROR = 'GET_COUNTRY_LIST_ERROR',
    RESET_GET_COUNTRY_LIST = 'RESET_GET_COUNTRY_LIST'
}

export type CovidActions =
    OverallListAction
    | CountryListAction;